In [5]:
import torch
import numpy as np

In [18]:
##############通过troch.tensor创建

arr = np.ones((3,3))
print(arr)

t = torch.tensor(arr)
print(t)
print("================================")
print(t.shape)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([3, 3])


In [19]:
####################通过torch.from_numpy创建
arr1 = np.array([[1,2,3],[4,5,6]])
t1 = torch.from_numpy(arr1)
print("numpy arr:",arr1)
print("tensor:",t1)

arr1[0][0] = -1
print("numpy arr:",arr1)
print("tensor:",t1)

t1[0,0] = -5
print("numpy arr:",arr1)
print("tensor:",t1)

numpy arr: [[1 2 3]
 [4 5 6]]
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
numpy arr: [[-1  2  3]
 [ 4  5  6]]
tensor: tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)
numpy arr: [[-5  2  3]
 [ 4  5  6]]
tensor: tensor([[-5,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


In [23]:
###################通过数值创建

out_t = torch.tensor([1])
t = torch.zeros((3,3),out = out_t)
print(t,'\n',out_t)
print(id(t),id(out_t),id(t)==id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
2819767161280 2819767161280 True


In [27]:
#########################full
t = torch.full((3,3),10)
print(t)
t1 = torch.full((2,3),8)
print(t1)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])
tensor([[8, 8, 8],
        [8, 8, 8]])


In [32]:
#############arange 等差张量
t = torch.arange(2,10,3)
print(t)

t1 = torch.arange(1,8,1)
print(t1)

tensor([2, 5, 8])
tensor([1, 2, 3, 4, 5, 6, 7])


In [38]:
#############linspce均分张量
t = torch.linspace(2,10,10)
print(t)

t1 = torch.linspace(1,10,10)
print(t1)

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [40]:
#######eye 对角矩阵张量
t = torch.eye(3,5)
print(t)

t = torch.eye(5,5)
print(t)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [10]:
# mean 张量 std张量
mean = torch.arange(1,5,dtype=torch.float)
std = torch.arange(1,5,dtype=torch.float)
t_normal = torch.normal(mean,std)
print(t_normal)

tensor([1., 2., 3., 4.])
tensor([-1.1264,  1.5874, -1.9374,  5.3314])


In [8]:
# mean 标量 std标量
t_normal = torch.normal(0.,1.,size=(4,))
print(t_normal)

tensor([ 0.0944,  1.1896, -0.4228,  2.0375])


In [9]:
# mean 张量 std标量
mean = torch.arange(1,5,dtype=torch.float)
std = 1
t_normal = torch.normal(mean,std)
print(t_normal)

tensor([1.8252, 2.2874, 2.7354, 3.7257])


In [11]:
#########随机序列
t = torch.randperm(10)
print(t)

tensor([2, 7, 6, 9, 4, 3, 1, 0, 5, 8])


In [32]:
#####################################################张量切分
a = torch.ones((2,7))
#print(a)
list_of_tensors = torch.chunk(a,dim=1,chunks=3)
print(list_of_tensors)
for x,t in enumerate(list_of_tensors):
    print("第{}个张量为:{},shape is {}".format(x+1,t,t.shape))
print("\n")
list_of_tensors = torch.chunk(a,dim=1,chunks=7)
for idx,t in enumerate(list_of_tensors):
    print("第{}个张量为:{},shape is {}".format(idx+1,t,t.shape))
print("\n")

a = torch.ones((2,5))
#print(a)
list_of_tensors = torch.split(a,dim=1,split_size_or_sections=[2,1,2])
for idx,t in enumerate(list_of_tensors):
    print("第{}个张量为:{},shape is {}".format(idx+1,t,t.shape))

(tensor([[1., 1., 1.],
        [1., 1., 1.]]), tensor([[1., 1., 1.],
        [1., 1., 1.]]), tensor([[1.],
        [1.]]))
第1个张量为:tensor([[1., 1., 1.],
        [1., 1., 1.]]),shape is torch.Size([2, 3])
第2个张量为:tensor([[1., 1., 1.],
        [1., 1., 1.]]),shape is torch.Size([2, 3])
第3个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])


第1个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第2个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第3个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第4个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第5个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第6个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第7个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])


第1个张量为:tensor([[1., 1.],
        [1., 1.]]),shape is torch.Size([2, 2])
第2个张量为:tensor([[1.],
        [1.]]),shape is torch.Size([2, 1])
第3个张量为:tensor([[1., 1.],
        [1., 1.]]),shape is torch.Size([

In [41]:
########################################张量索引
#index_select
t = torch.randint(0,9,size=(3,3))
idx = torch.tensor([0,2],dtype=torch.long)
t_selet = torch.index_select(t,dim=1,index=idx)
print("t:\n{}\nt_select:\n{}".format(t,t_selet))
idx = torch.tensor([0],dtype=torch.long)
t_selet = torch.index_select(t,dim=1,index=idx)
print("t:\n{}\nt_select:\n{}".format(t,t_selet))


t:
tensor([[4, 6, 4],
        [0, 6, 0],
        [5, 8, 6]])
t_select:
tensor([[4, 4],
        [0, 0],
        [5, 6]])
t:
tensor([[4, 6, 4],
        [0, 6, 0],
        [5, 8, 6]])
t_select:
tensor([[4],
        [0],
        [5]])


In [44]:
#masked_select
t = torch.randint(0,9,size=(3,3))
print(t)
mask = t.gt(5)
t_selet = torch.masked_select(t,mask)
print(mask)
print("t:\n{}\nt_select:\n{}".format(t,t_selet))

tensor([[0, 0, 6],
        [1, 1, 3],
        [7, 4, 8]])
tensor([[False, False,  True],
        [False, False, False],
        [ True, False,  True]])
t:
tensor([[0, 0, 6],
        [1, 1, 3],
        [7, 4, 8]])
t_select:
tensor([6, 7, 8])
