In [2]:
import torch 
import numpy as np

In [4]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
arr = np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
